# Generated by Django 2.0.6 on 2018-07-12 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
